---
resources:
  - name: test-repository
    type: git
    source:
      uri: https://github.com/bipin1086/gitpipeline.git
      branch: main

jobs:
  - name: job-list-files
    public: true
    plan:
      - get: test-repository
      - task: list-files
        file: gitpipeline/tasks/list-files.yml
